/*-
 * Copyright (c) 2014 Jason Lingle
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the author nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * This program uses libgcrypt to generate the (P,Q,G) parameters for DSA
 * signatures. It is deliberately not part of the build system since
 *
 * (a) All builds will need to use the same parms, and the output from this
 *     program is not reproduceable and thus needs to be checked in anyway.
 *
 * (b) libpraefectus does not itself use libgcrypt, so there's no sense adding
 *     a hard dependency on libgcrypt when we only use it to generate the
 *     parameters.
 *
 * This program doesn't bother releasing memory due to its short lifetime.
 *
 * Build with
 *   cc -ogen-dsa-parms gen-dsa-parms.c `libgcrypt-config --cflags --libs`
 *
 * GNU users may need to include
 *   -I/usr/include/bsd
 */
#include <stdio.h>
#include <stdlib.h>
#include <sysexits.h>
#include <err.h>

#include <gcrypt.h>

/* By DSA standards, these are fairly week, but we don't need the generated
 * signatures to be secure for than several hours at a time, and keeping the
 * signatures small is important.
 */
#define L 512
#define N 128

static int check_prime(void* _, int mode, gcry_mpi_t candidate) {
  return !gcry_prime_check(candidate, 0);
}

int main(void) {
  gcry_mpi_t p, q, g, two, * factors;
  gcry_error_t error;
  unsigned char buffer[1024];

  /* Initialise gcrypt */
  if (!gcry_check_version(GCRYPT_VERSION))
    errx(EX_SOFTWARE, "libgcrypt version mismatch");
  gcry_control(GCRYCTL_DISABLE_SECMEM, 0);
  gcry_control(GCRYCTL_INITIALIZATION_FINISHED, 0);

  if ((error = gcry_prime_generate(
         /* For whatever reason, this produces factors that actually have (n+2)
          * bits, so offset input by -2 to compensate.
          */
         &p, L, N-2, &factors, check_prime, NULL,
         /* This information is public, so random quality is not a concern */
         GCRY_WEAK_RANDOM, 0)))
    errx(EX_UNAVAILABLE,
         "Error genererating P: %s", gcry_strerror(error));

  /* While the factors_nbits requires a factor of p-1 to be N bits long, it
   * doesn't actually filter the factors list. Do this manually.
   */
  while (*factors && gcry_mpi_get_nbits(*factors) != N)
    ++factors;

  if (!*factors)
    errx(EX_UNAVAILABLE, "Unable to filter factors list for Q");

  q = *factors;

  g = gcry_mpi_copy(p);
  gcry_mpi_sub_ui(g, g, 1);
  gcry_mpi_div(g, NULL, g, q, 0);
  two = gcry_mpi_new(2);
  gcry_mpi_set_ui(two, 2);
  gcry_mpi_powm(g, two, g, p);

  printf("/* This file was generated by gen-dsa-parms.c. */\n");
  printf("#ifndef LIBPRAEFECTUS_DSA_PARMS_H_\n");
  printf("#define LIBPRAEFECTUS_DSA_PARMS_H_\n");
  printf("#define PRAEF_DSA_L %d\n", L);
  printf("#define PRAEF_DSA_N %d\n", N);
  gcry_mpi_print(GCRYMPI_FMT_HEX, buffer, sizeof(buffer), NULL, p);
  printf("#define PRAEF_DSA_P \"%s\"\n", buffer);
  gcry_mpi_print(GCRYMPI_FMT_HEX, buffer, sizeof(buffer), NULL, q);
  printf("#define PRAEF_DSA_Q \"%s\"\n", buffer);
  gcry_mpi_print(GCRYMPI_FMT_HEX, buffer, sizeof(buffer), NULL, g);
  printf("#define PRAEF_DSA_G \"%s\"\n", buffer);
  printf("#endif /* LIBPRAEFECTUS_DSA_PARMS_H_ */\n");
  return 0;
}
